### ISSUE TITLE
Explore button in home page not working

### ISSUE THREAD

**Issue by MayaSatishRao** [A-BMT02/snippets#10]
When you click on Explore button in the landing page, it does not take you to explore page. Also, if I click on the snippets logo, it does not take you to homepage. Can I work on this issue?

**Comment by A-BMT02** [comment]
The "Explore" button on the home page has been fixed => https://github.com/A-BMT02/snippets/pull/11
You can go ahead and work on the 'snippets' logo

Thank you for your time @MayaSatishRao

**Comment by MayaSatishRao** [comment]
I have made a pull request. Could you check and merge if it is ok?

**Comment by MayaSatishRao** [comment]
There seems to be a problem in deployment. Should I make another pull request?? @A-BMT02

**Comment by A-BMT02** [comment]
What do you mean by problem in deployment? @MayaSatishRao

**Comment by MayaSatishRao** [comment]
![g4](https://user-images.githubusercontent.com/67920373/194106314-539703b7-b58d-4f71-8fd7-13fc0ffad3ad.png)
There is an error in deployment.

**Comment by A-BMT02** [comment]
Yes, check the comments i made on your previous pull request
The last one should be the one that caused the error 

You can fix that and push to same branch. No need to make a new pull request

**Comment by MayaSatishRao** [comment]
I have made the changes and there are no errors from Vercel. Should I close the pull request now?

**Comment by A-BMT02** [comment]
I merged and closed it @MayaSatishRao 

Thank you for contributing!
