### ISSUE TITLE
UI enhancement : button without pointer

### ISSUE THREAD

**Issue by iceddrop** [A-BMT02/snippets#13]
Hi, I went through your create snippet page and noticed the 'save' button at the bottom of the page does not have a pointer on hover. I'll like to resolve that.
![image_2022-10-06_141903083](https://user-images.githubusercontent.com/93996532/194323311-82795a38-b8f2-4930-9810-9113135c7ac4.png)

**Comment by A-BMT02** [comment]
Go ahead @iceddrop 

Thanks for checking out the project!
