### ISSUE TITLE
on hover (explore button) the img is pushed down

### ISSUE THREAD

**Issue by glopzel** [A-BMT02/snippets#15]
Hi! when you hover on the explore button (landing page/ index.js) the image is slightly pushed down so it looks a bit weird. I'd like to send a small PR to correct it. 

https://user-images.githubusercontent.com/74939915/194768654-991dd650-4341-4f0c-9fdd-9b1d20201b86.mov

**Comment by Adish90k** [comment]
This is happening because you are giving the element and border on hover whereas before it do not have a border so on hover an border appears and because of that the elements height changes

**Comment by A-BMT02** [comment]
Hey @glopzel 
I'll assign you to this issue 
You can go ahead and send the pr

Thank you for checking out the project!

**Comment by Adish90k** [comment]
i fixed the issue and made a pull request

**Comment by A-BMT02** [comment]
Both of you made a valid pull request that fixes the issue. But I'm going to go ahead and merge @glopzel pull request because she
1. removed the unnecessary portion of the code.
2. Opened the issue 

But thank you for contributing @Adish90k
