### ISSUE TITLE
No available open issues

### ISSUE THREAD

**Issue by adamako** [A-BMT02/snippets#24]
Hi there, it's my first time to participate to Hacktoberfest.
I want to contribute to this project but I saw that there is no available open issue. 
Is the project already finished or what can I do ?

Thanks !

**Comment by A-BMT02** [comment]
Hey @adamako , You can go through the website to see if there's anything that can be improved 

Thanks for checking out the project

**Comment by adamako** [comment]
Okay 👍🏾
