### ISSUE TITLE
Cannot run project locally

### ISSUE THREAD

**Issue by peterintech** [A-BMT02/snippets#5]
So I followed the steps in the readme, but couldn't run the local development server, it first requested that i put the static folder in a public folder which i did, and then talked about not having a production build. All error was pointing at using deprecated package, do check and rectify it, i wanna contribute

**Comment by A-BMT02** [comment]
Hey @iampitrus , Thank you for taking you time to explore the project 

You seem to be the only one having this problem, did you install the dependencies with ```` npm install ```` before running the local server ? 

Also if you can post a screenshot of the error here, it will help us debunk it 
Thank you
